# Copyright (c) 2023 Saglabs SA. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Debian 12
FROM debian:bookworm

ARG MFS_VERSION

# Install wget, lsb-release and curl
RUN apt update && \
    apt install -y wget lsb-release curl fuse libfuse3-dev tree ca-certificates e2fsprogs gnupg2 && \
    # security updates
    apt install -y apt systemd

# Add key
RUN curl https://repository.moosefs.com/moosefs.key | gpg -o /etc/apt/keyrings/moosefs.gpg --dearmor
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/moosefs.gpg] http://repository.moosefs.com/moosefs-4/apt/debian/bookworm bookworm main" > /etc/apt/sources.list.d/moosefs.list

# Install MooseFS client
RUN apt update --allow-releaseinfo-change && apt install -y moosefs-client=${MFS_VERSION}

# Copy the CSI plugin
COPY moosefs-csi-plugin /bin/

ENTRYPOINT ["/bin/moosefs-csi-plugin"]
